// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260516224847_CreateDb")]
    partial class CreateDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Entities.AdministrativeUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdministrativeUnits");
                });

            modelBuilder.Entity("Infrastructure.Entities.OperationalGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid>("StrategicGoalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("StrategicGoalId");

                    b.ToTable("OperationalGoals");
                });

            modelBuilder.Entity("Infrastructure.Entities.ProgramTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid>("OperationalGoalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OperationalGoalId");

                    b.ToTable("ProgramTasks");
                });

            modelBuilder.Entity("Infrastructure.Entities.StrategicGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("StrategicGoals");
                });

            modelBuilder.Entity("Infrastructure.Entities.Strategy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AdministrativeUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("AdministrativeUnitId");

                    b.ToTable("Strategies");
                });

            modelBuilder.Entity("Infrastructure.Entities.OperationalGoal", b =>
                {
                    b.HasOne("Infrastructure.Entities.StrategicGoal", "StrategicGoal")
                        .WithMany("OperationalGoals")
                        .HasForeignKey("StrategicGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StrategicGoal");
                });

            modelBuilder.Entity("Infrastructure.Entities.ProgramTask", b =>
                {
                    b.HasOne("Infrastructure.Entities.OperationalGoal", "OperationalGoal")
                        .WithMany("ProgramTasks")
                        .HasForeignKey("OperationalGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperationalGoal");
                });

            modelBuilder.Entity("Infrastructure.Entities.StrategicGoal", b =>
                {
                    b.HasOne("Infrastructure.Entities.Strategy", "Strategy")
                        .WithMany("StrategicGoals")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("Infrastructure.Entities.Strategy", b =>
                {
                    b.HasOne("Infrastructure.Entities.AdministrativeUnit", "AdministrativeUnit")
                        .WithMany("Strategies")
                        .HasForeignKey("AdministrativeUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdministrativeUnit");
                });

            modelBuilder.Entity("Infrastructure.Entities.AdministrativeUnit", b =>
                {
                    b.Navigation("Strategies");
                });

            modelBuilder.Entity("Infrastructure.Entities.OperationalGoal", b =>
                {
                    b.Navigation("ProgramTasks");
                });

            modelBuilder.Entity("Infrastructure.Entities.StrategicGoal", b =>
                {
                    b.Navigation("OperationalGoals");
                });

            modelBuilder.Entity("Infrastructure.Entities.Strategy", b =>
                {
                    b.Navigation("StrategicGoals");
                });
#pragma warning restore 612, 618
        }
    }
}
